### ISSUE TITLE
individuare aggiornamento tavola 

### ISSUE THREAD

**Issue by francesco-de-napoli** [ondata/guida-api-istat#11]
Buongiorno,
ho la necessità di aggiornare i dati attraverso SDMXWS di una certa tavola solo quando i dati sottostanti vengono aggiornati, volevo chiedere se vi è un parametro che individui la data di aggiornamento di una tavola Istat (versione/data aggiornamento)?

**Comment by aborruso** [comment]
Buongiorno @francesco-de-napoli purtroppo credo che questa informazione non sia esposta via SDMX.

Istat nella pagina dedicata https://www.istat.it/it/metodi-e-strumenti/web-service-sdmx nel menù "Aggiornamento dei dataset e relative query" indica i dataset aggiornati recentemente.

Si potrebbe fare un webscraping quotidiano per vedere se c'è l'aggiornamento del dataset interessato (può essere una soluzione).

Io lo realizzerò non appena possibile

**Comment by francesco-de-napoli** [comment]
Grazie mille per la risposta, ho realizzato il batch e volevo chiedere se sa il tempo di permanenza medio di ciascuna tavola nel menù "Aggiornamento dei dataset e relative query" per schedulare il batch (giornaliero/settimanale oppure se farlo girare più volte al giorno). Grazie

**Comment by aborruso** [comment]
@francesco-de-napoli nella mia esperienza un check giornaliero basta e avanza.

Hai usato questa guida? Ti è tornata utile?
Fa sempre piacere avere un riscontro

Grazie

**Comment by francesco-de-napoli** [comment]
Si ho usato questa guida ed è stata davvero molto utile. Ho scritto un codice Python che legge da un Excel l'ID delle tavole da tenere sotto controllo e la relativa ultima data di aggiornamento. Dal menù  "Aggiornamento dei dataset e relative query" estraggo l'ID delle tavole e la relativa data di aggiornamento e le confronto con le Excel. Se per una certa tavola le due date non coincidono viene eseguito il comando API REST per scaricare la tavola. 
Il batch richiama il programma Python sopra descritto.
Grazie ancora.

**Comment by francesco-de-napoli** [comment]
Ciao, scusami ancora il disturbo, scaricando la tavola dal comando API SDMX e salvandola in formato csv come posso ottenere i nomi delle singole voci della spalletta così come viene scaricata da i.stat manualmente? Mi sembra che il campo TIPO_DATO identifica univocamente le singole voci della spalletta ma volevo sapere se esiste una tabella di trascodifica per ottenere la descrizioni di tali voci. Grazie mille per la disponibilità.
