### ISSUE TITLE
Ottenere elenco codici/valori

### ISSUE THREAD

**Issue by aborruso** [ondata/guida-api-istat#13]
Ciao, scusami ancora il disturbo, scaricando la tavola dal comando API SDMX e salvandola in formato csv come posso ottenere i nomi delle singole voci della spalletta così come viene scaricata da i.stat manualmente? Mi sembra che il campo TIPO_DATO identifica univocamente le singole voci della spalletta ma volevo sapere se esiste una tabella di trascodifica per ottenere la descrizioni di tali voci. Grazie mille per la disponibilità.

_Originally posted by @francesco-de-napoli in https://github.com/ondata/guida-api-istat/issues/11#issuecomment-864119907_

**Comment by aborruso** [comment]
@francesco-de-napoli trovi come farlo qui https://ondata.github.io/guida-api-istat/#schema-dati

**Comment by francesco-de-napoli** [comment]
Ok ma una volta che conosco i valori che assume una certa dimensione (campo) come li posso mappare in modo tale che il csv contenga i valori piuttosto che i codici?

**Comment by aborruso** [comment]
Ciao @francesco-de-napoli non c'è modo, l'output è con i codici. A te poi fare il JOIN

**Comment by francesco-de-napoli** [comment]
Ok, ti ringrazio.
