### ISSUE TITLE
cambio colonne tavola turisti

### ISSUE THREAD

**Issue by francesco-de-napoli** [ondata/guida-api-istat#14]
Buongiorno,
grazie alla vostra guida abbiamo creato degli script Python per scaricare ogni mese alcune tavole istat.
Fino al mese precedente lanciavamo il seguente comando:

subprocess.run('curl -kL -H "Accept: application/vnd.sdmx.data+csv;version=1.0.0" "http://sdmx.istat.it/SDMXWS/rest/data/122_54/M.551_553.N.WORLD.IT.TOT.ALL.ALL.NI.ALL.ALL" >'+path_input+'/Presenza_turisti.csv', shell=True)  

Per questo mese invece abbiamo dovuto lanciare questo comando:

subprocess.run('curl -kL -H "Accept: application/vnd.sdmx.data+csv;version=1.0.0" "http://sdmx.istat.it/SDMXWS/rest/data/122_54/M.551_553.N.WORLD.IT.TOT.ALL.NI.ALL.ALL.ALL" >'+path_input+'/Presenza_turisti.csv', shell=True)  

poichè è cambiato l'ordine delle colonne della tavola.
Vorrei chiedervi ogni quanto cambiano le colonne di una tavola e di conseguenza anche i filtri da applicare?
Avendo diverse tavole da scaricare è possibile creare qualcosa di automatico oppure ogni volta che serve una tavola bisogna rifare l'analisi dei filtri?
Grazie mille per la collaborazione e per quanto avete fatto finora.

**Comment by francesco-de-napoli** [comment]
Ciao, scusami se ti rispondo solo ora ma probabilmente mi ero sbagliato io (non riesco a replicare il caso d'uso che mi restituiva l'errore).
Quindi ancora grazie mille per il supporto!!

**Comment by francesco-de-napoli** [comment]
Ciao, scusami se ti disturbo ancora ma ho trovato lo use case di cui parlavo. Non so se mi sto perdendo qualcosa.

La tavola in questione è  quella relativa ai conti della protezione sociale (**id = 97_366**).
Lo schema dati della tavola (http://sdmx.istat.it/SDMXWS/rest/datastructure/IT1/DCCN_PROTSOC) contiene il campo **TIPO_AGGR** mentre scaricando la tavola con il comando:
curl -kL -H "Accept: application/vnd.sdmx.data+csv" "http://sdmx.istat.it/SDMXWS/rest/data/97_366">
La tavola contiene il campo **TIPO_DATO** e non **TIPO_AGGR**.
Grazie mille per la collaborazione e la disponibilità.

**Comment by aborruso** [comment]
Ciao @francesco-de-napoli ho verificato quanto hai scritto.
Anche a me sembra un errore.

Prova a contattarli per segnalare la cosa: https://www.istat.it/it/contatti
