### ISSUE TITLE
Il livello di dettaglio tra "dati.istati.it" e "sdmx.istat.it" è lo stesso?

### ISSUE THREAD

**Issue by Catergae** [ondata/guida-api-istat#19]
Salve a tutti, ho notato a differenza della banca dati online attraverso le API REST non è possibile raggiungere lo stesso livello di dettaglio. Per esempio avevo bisogno di estrarre il conteggio dei delitti di peculato e corruzione e nel sito ho la possibilità di filtrare per queste tipologie come visibile nell'immagine sotto allegata.

![delitti](https://user-images.githubusercontent.com/123557396/216919492-caeab70f-5f29-4292-941b-c4617418929e.png)

Al contrario con le chiamate GET ho notato che una volta individuato il relativo Dataflow:
"_73_67 Delitti denunciati dalle forze di polizia all'autorità giudiziaria_"

mandando la successiva GET per individuare i filtri applicabili si ottengono le seguenti tipologie di delitto: (screenshot della chiamata "_Available constratint XML_")

![filtriDelitti](https://user-images.githubusercontent.com/123557396/216921606-7fd09c14-65dc-4ab0-bb78-bc37d10b1676.jpg)

Non sono presenti le stesse tipologie di delitti che sono invece nel sito.

Pertanto volevo sapere se c'è una corrispondenza esatta anche a livello di granularità del dato tra la banca dati online "[dati.istat.it](http://dati.istat.it/?lang=it&SubSessionId=e5f618e5-26b3-414e-9dfa-9510761c618f#)" e il sistema SDMX; oppure sono io che sto sbagliando qualcosa nelle chiamate.

Premetto che sono un neofita e sono partito seguendo i passaggi della guida fatta molto bene delle chiamate tramite POSTMAN. Da quanto ho capito gli step sono i seguenti:
GET del _Dataflow_ per individuare il _Datasource_ -> GET del _Datasource_ per individuare le variabili presenti -> GET _Codelist_ per individuare le modalità delle variabili -> GET _Available Constraint_ per indivudare i filtri applicabili.

**Comment by patrunomeister** [comment]
E' opportuno utilizzare il nuovo sistema esploradati. E' in corso la migrazione di dati.istat.it sul nuovo sistema, per cui a breve verrà dismesso. Per quanto riguarda la GET precedente, sul nuovo sistema diventa 

https://esploradati.istat.it/SDMXWS/rest/data/73_1187/...CP322BIS.../?startPeriod=2014&endPeriod=2019
