### ISSUE TITLE
Come avere la descrizione dei dati?

### ISSUE THREAD

**Issue by JikuRoby** [ondata/guida-api-istat#21]
Ciao, 
intanto grazie per la guida.

Sto riscontrando un problema e non ne sto cavando piede, scarico i dati e tra i tanti ricevo (esempio ID dati 24_84):

`Final data structure: {
  "filters": [
    {
      "id": "FREQ",
      "values": [
        "A"
      ]
    },
    {
      "id": "STATO_CIV_SPOSA",
      "values": [
        "1",
        "16",
        "17",
        "3",
        "4",
        "99"
      ]
    },
    {
      "id": "STATO_CIV_SPOSO",
      "values": [
        "99",
        "1",
        "16",
        "17",
        "3",
        "4"
      ]
    },
    {
      "id": "TIPO_DATO",
      "values": [
        "MAGEMBR_110",
        "MAGEMBR_16_49",
        "MAGEMBR_FROM2017",
        "MAGEMBR16_49FROM2017",
        "MAGEMBRGR_110",
        "MAGEMBRGR_16_49",
        "MAGEMBRGR_FROM2017",
        "MAGEMBRGR16_49FROM2017",
        "BRASM_110",
        "BRASM_FROM2017",
        "BRGRASM_110",
        "BRGRASM_FROM2017",
        "CMARRGP_110",
        "CMARRGP_FROM2017",
        "FMRBR_110",
        "FMRBR_FROM2017",
        "FMRBRALL_110",
        "FMRBRALL_FROM2017",
        "FMRBRGR_110",
        "FMRBRGR_FROM2017",
        "FMRBRGRALL_110",
        "FMRBRGRALL_FROM2017",
        "JOWNPP_110",
        "JOWNPP_FROM2017",
        "MARALFSP_110",
        "MARALFSP_FROM2017",
        "NUPRATEIND_FROM2017",
        "NUPT_TOTM_110",
        "NUPT_TOTM_AGE",
        "NUPT_TOTM_FROM2017",
        "NUPT_TOTM_TAGE",
        "NUPT_TOTW_110",
        "NUPT_TOTW_AGE",
        "NUPT_TOTW_FROM2017",
        "NUPT_TOTW_TAGE",
        "NUPTRATE_110",
        "NUPTRATE_FROM2017",
        "PERCCIVMAR_FROM2017"
      ]
    }
  ],
`

Però vorrei la descrizione, per esempio nel sito abbiamo:

`[FMRBR_FROM2017] indice di primo nuzialità  spose (16-49 anni) - valori per mille`

Ma quando scarico non mi restituisce la descrizione ma solo `FMRBR_FROM2017` stesso discorso per `STATO_CIV_SPOSO` dove ci sono i valori ma non si sa a cosa corrispondino. 

In pratica vorrei creare dei filtri nella mia interfaccia ma senza descrizione diventa difficile.

Esiste un metodo, un qualche posto dove si possano avere tramite API? Grazie mille

**Comment by aborruso** [comment]
Ciao @JikuRoby ,
nella guida mi sembra riportato come fare. È quella in cui leggi

> Ma qual è il **significato** di `FREQ`, `ESITO`, `ITTER107`,`TIPO_DATO` e `SELECT_TIME`?

Vado al tuo esempio di `STATO_CIV_SPOSO`:

```xml
            <structure:Dimension id="STATO_CIV_SPOSO" urn="urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=IT1:DCIS_MATRIND(1.4).STATO_CIV_SPOSO" position="4">
              <structure:ConceptIdentity>
                <Ref id="STATO_CIV_SPOSO" maintainableParentID="VARIAB_ALL" maintainableParentVersion="22.0" agencyID="IT1" package="conceptscheme" class="Concept" />
              </structure:ConceptIdentity>
              <structure:LocalRepresentation>
                <structure:Enumeration>
                  <Ref id="CL_STATCIV2" version="4.1" agencyID="IT1" package="codelist" class="Codelist" />
                </structure:Enumeration>
              </structure:LocalRepresentation>
            </structure:Dimension>
```

La `codelist` del caso ha ID `CL_STATCIV2`, per estrarne i valori dovrai quindi chiamare questo URL:

<https://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_STATCIV2>

Era quello che cercavi?

**Comment by aborruso** [comment]
E per `TIPO_DATO` la codelist è <https://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_TIPO_DATO15>

**Comment by JikuRoby** [comment]
@aborruso grazie mille. Si sembra quello, però non capisco perchè se faccio: https://sdmx.istat.it/SDMXWS/rest/data/24_84

Tra i dati ricevo:

`TIPO_DATO
MAGEMBR_110
MAGEMBR_16_49
MAGEMBR_FROM2017
MAGEMBR16_49FROM2017
MAGEMBRGR_110
MAGEMBRGR_16_49
MAGEMBRGR_FROM2017
MAGEMBRGR16_49FROM2017
BRASM_110
BRASM_FROM2017
BRGRASM_110
BRGRASM_FROM2017
CMARRGP_110
CMARRGP_FROM2017
FMRBR_110
FMRBR_FROM2017
FMRBRALL_110
FMRBRALL_FROM2017
FMRBRGR_110
FMRBRGR_FROM2017
FMRBRGRALL_110
FMRBRGRALL_FROM2017
JOWNPP_110
JOWNPP_FROM2017
MARALFSP_110
MARALFSP_FROM2017
NUPRATEIND_FROM2017
NUPT_TOTM_110
NUPT_TOTM_AGE
NUPT_TOTM_FROM2017
NUPT_TOTM_TAGE
NUPT_TOTW_110
NUPT_TOTW_AGE
NUPT_TOTW_FROM2017
NUPT_TOTW_TAGE
NUPTRATE_110
NUPTRATE_FROM2017
PERCCIVMAR_FROM2017`

Ma questi non corrispondono a questi qui https://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_TIPO_DATO15

Dove sto sbagliando?

**Comment by aborruso** [comment]
Ciao @JikuRoby per fare debug, è meglio fare esempi piccoli.

Nel tuo esempio ad esempio c'è il valore `MAGEMBR_110`, che io trovo qui https://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_TIPO_DATO15

```xml
<structure:Code id="MAGEMBR_110" urn="urn:sdmx:org.sdmx.infomodel.codelist.Code=IT1:CL_TIPO_DATO15(4.1).MAGEMBR_110">
<common:Name xml:lang="it">età media al matrimonio spose (tutte le età) secondo il territorio al Censimento 2011 (110 province)</common:Name>
<common:Name xml:lang="en">mean age at marriage brides by geographical area at 2011 census (all ages)</common:Name>
</structure:Code>
```

Fammi un esempio di valore che non trovi (io qui ne ho guardato solo uno e c'è)

**Comment by JikuRoby** [comment]
Per esempio prendi questo: ALJPD che troviamo qui https://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_TIPO_DATO15

Ma se scarico da qui: https://sdmx.istat.it/SDMXWS/rest/data/24_84 non c'è ALJPD

**Comment by aborruso** [comment]
@JikuRoby mi confermi quindi che

```
TIPO_DATO MAGEMBR_110 MAGEMBR_16_49 MAGEMBR_FROM2017 MAGEMBR16_49FROM2017 MAGEMBRGR_110 MAGEMBRGR_16_49 MAGEMBRGR_FROM2017 MAGEMBRGR16_49FROM2017 BRASM_110 BRASM_FROM2017 BRGRASM_110 BRGRASM_FROM2017 CMARRGP_110 CMARRGP_FROM2017 FMRBR_110 FMRBR_FROM2017 FMRBRALL_110 FMRBRALL_FROM2017 FMRBRGR_110 FMRBRGR_FROM2017 FMRBRGRALL_110 FMRBRGRALL_FROM2017 JOWNPP_110 JOWNPP_FROM2017 MARALFSP_110 MARALFSP_FROM2017 NUPRATEIND_FROM2017 NUPT_TOTM_110 NUPT_TOTM_AGE NUPT_TOTM_FROM2017 NUPT_TOTM_TAGE NUPT_TOTW_110 NUPT_TOTW_AGE NUPT_TOTW_FROM2017 NUPT_TOTW_TAGE NUPTRATE_110 NUPTRATE_FROM2017 PERCCIVMAR_FROM2017
```

sono in sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_TIPO_DATO15?

Per fare debug, fissiamo un punto e poi passiamo a un altro. Grazie per la collaborazione

**Comment by JikuRoby** [comment]
Ti dico meglio la logica che applicato:

1. trovo il codice ID es. 24_84
2. faccio una request e fecth
3. costruisco il json:

`Fetching data for code: 24_84
Final data structure: {
  "filters": [
    {
      "id": "FREQ",
      "values": [
        "A"
      ]
    },
    {
      "id": "STATO_CIV_SPOSA",
      "values": [
        "1",
        "16",
        "17",
        "3",
        "4",
        "99"
      ]
    },
    {
      "id": "STATO_CIV_SPOSO",
      "values": [
        "99",
        "1",
        "16",
        "17",
        "3",
        "4"
      ]
    },
    {
      "id": "TIPO_DATO",
      "values": [
        "MAGEMBR_110",
        "MAGEMBR_16_49",
        "MAGEMBR_FROM2017",
        "MAGEMBR16_49FROM2017",
        "MAGEMBRGR_110",
        "MAGEMBRGR_16_49",
        "MAGEMBRGR_FROM2017",
        "MAGEMBRGR16_49FROM2017",
        "BRASM_110",
        "BRASM_FROM2017",
        "BRGRASM_110",
        "BRGRASM_FROM2017",
        "CMARRGP_110",
        "CMARRGP_FROM2017",
        "FMRBR_110",
        "FMRBR_FROM2017",
        "FMRBRALL_110",
        "FMRBRALL_FROM2017",
        "FMRBRGR_110",
        "FMRBRGR_FROM2017",
        "FMRBRGRALL_110",
        "FMRBRGRALL_FROM2017",
        "JOWNPP_110",
        "JOWNPP_FROM2017",
        "MARALFSP_110",
        "MARALFSP_FROM2017",
        "NUPRATEIND_FROM2017",
        "NUPT_TOTM_110",
        "NUPT_TOTM_AGE",
        "NUPT_TOTM_FROM2017",
        "NUPT_TOTM_TAGE",
        "NUPT_TOTW_110",
        "NUPT_TOTW_AGE",
        "NUPT_TOTW_FROM2017",
        "NUPT_TOTW_TAGE",
        "NUPTRATE_110",
        "NUPTRATE_FROM2017",
        "PERCCIVMAR_FROM2017"
      ]
    }
  ],
  "time": [
    "2004",
    "2005",
    "2006",
    "2007",
    "2008",
    "2009",
    "2010",
    "2011",
    "2012",
    "2013",
    "2014",
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021"
  ],
  "geo": [
    {
      "code": "IT",
      "name_it": "Italia",
      "coordinates": {
        "longitude": 12.56738,
        "latitude": 41.87194
      }
    },
    {
      "code": "IT108",
      "name_it": "Monza e della Brianza",
      "coordinates": {
        "longitude": 9.258801499999999,
        "latitude": 45.623599
      }
    },...
`
Quei valori tipo `STATO_CIV_SPOSO` o `TIPO_DATO` li trovo in automatico, non ho un ID preciso, dipende da quello che si trova, perchè ho creato la lista degli argomenti, clicco e prendo l'ID poi faccio la request, quindi non li conosco a monte.

Però quando li scarico, puoi notare che i valori non sono descrittivi:

`      "id": "TIPO_DATO",
      "values": [
        "MAGEMBR_110",
        "MAGEMBR_16_49",...`
        
        Io vorrei usare questi come filtri, funziona però non essendo descrittivi non ho idea di cosa significhino quei valori

**Comment by aborruso** [comment]
Ciao @JikuRoby mi sto un po' perdendo :(

E quello che farò adesso è un po' riscrivere la guida.

Sei interessato a `24_84`. Scarichi il dataset e hai lo schema dati descritto in `DCIS_MATRIND.xml`:

<https://sdmx.istat.it/SDMXWS/rest/datastructure/IT1/DCIS_MATRIND/>

Da questo puoi automatizzare estrazione campi e accoppiarli con in campi che ti ritrovi in `24_84`. Tra questi ad esempio `TIPO_DATO`, che contiene dei codici, in particolare questi 38:

```
BRASM_110
BRASM_FROM2017
BRGRASM_110
BRGRASM_FROM2017
CMARRGP_110
CMARRGP_FROM2017
FMRBRALL_110
FMRBRALL_FROM2017
FMRBRGRALL_110
FMRBRGRALL_FROM2017
FMRBRGR_110
FMRBRGR_FROM2017
FMRBR_110
FMRBR_FROM2017
JOWNPP_110
JOWNPP_FROM2017
MAGEMBR16_49FROM2017
MAGEMBRGR16_49FROM2017
MAGEMBRGR_110
MAGEMBRGR_16_49
MAGEMBRGR_FROM2017
MAGEMBR_110
MAGEMBR_16_49
MAGEMBR_FROM2017
MARALFSP_110
MARALFSP_FROM2017
NUPRATEIND_FROM2017
NUPTRATE_110
NUPTRATE_FROM2017
NUPT_TOTM_110
NUPT_TOTM_AGE
NUPT_TOTM_FROM2017
NUPT_TOTM_TAGE
NUPT_TOTW_110
NUPT_TOTW_AGE
NUPT_TOTW_FROM2017
NUPT_TOTW_TAGE
PERCCIVMAR_FROM2017
```

Dallo schema dati ricavi che il significato è nella codelist `CL_TIPO_DATO15`. Fai una chiamata alle API della codelist <https://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_TIPO_DATO15> e per ogni chiave di sopra ti estrai la descrizione.

Non è questo il tuo obiettivo?

È tutto inseribile in una pipeline programmatica.

**Comment by JikuRoby** [comment]
Perdonami e grazie tante per aiutare.

Allora io ho la lista degli argomenti, li ho presi dal dataflow: [https://ondata.github.io/guida-api-istat/rawdata/dataflow.xml](url)

Ognuno di questi ha il suo ID, per esempio Matrimoni - Indicatori ha il codice `24_84` quindi scarico tutto usando: [https://sdmx.istat.it/SDMXWS/rest/data/24_84](url)

Questo perché ho bisogno di costruire una mappa, una timeline e un set di filtri.

Quindi mi sa sto sbagliando, dovrei non fare una chiamata usando `https://sdmx.istat.it/SDMXWS/rest/data/` ma dalla lista prendere `dataset e hai lo schema dati` quindi non tanto `24_84` ma `DCIS_MATRIND` e poi per ogni campo fare chiamate diverse per prendere i filtri, il tempo e i territori, confermi? Che giro! :)

**Comment by aborruso** [comment]
I dati grezzi sono espressi per diversi campi come codici. `24_84` è il dataflow, il dataflow diciamo che sono i dati grezzi di `DCIS_MATRIND`.

`DCIS_MATRIND` ha uno schema da cui puoi ricavare la codelist per ogni campo e le coppie chiave valore, da cui estrarre il significato dei codici che hai in alcuni campi dei dati grezzi.

È tutto tenuto separato per non avere dataset inutilmente grandi e perché certi attributi sono utili in più di un dataflow, e per ogni dataflow puoi avere un numero diversi di valori distinti.

**Comment by JikuRoby** [comment]
OK mi sa ho capito (spero!), quindi  giusto una cosa, hai detto:

`DCIS_MATRIND ha uno schema da cui puoi ricavare la codelist per ogni campo e le coppie chiave valore, da cui estrarre il significato dei codici che hai in alcuni campi dei dati grezzi.`

Come trovi le associazioni ai valori?

Io farei così da quello che ho capito:

1. prendi tutti i dati grezzi dal dataflow 24_84
2. prendi i campi quali `TIPO_DATO`
3. vai poi nello schema `DCIS_MATRIND`
4. sostituisci le label delle checkboxes con i valori descrittivi trovati nello schema
5. costruisci l'interfaccia

Questo perchè ho bisogno di tutti i dati che poi filtro per tempo, territorio e filtri delle checkboxes descrittivi

**Comment by aborruso** [comment]
@JikuRoby mi devo fermare un po' adesso. Ma credo che tu ora abbia tutti gli elementi per costruire la tua pipeline.

Le modalità dipendono anche dagli obiettivi che hai, dal linguaggio che usi, ecc..

**Comment by JikuRoby** [comment]
Va bene grazie mille :)

Metto qui 2 json che potrebbero essere utili:

1. ho notato che qui [https://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_ITTER107](url)
ci sono tutti i territori, con codici istat e nuts codes

2. ho creato uno script con google maps e geocoding, quindi ho creato un json dove ogni comune o regione ecc, comprensivi dei propri nuts o codici istat, abbiano anche le coordinate

3. nota bene, alcuni sono distretti o territori non precisi, quindi questi hanno le stesse coordinate:

```
              "coordinates": {
                "longitude": 12.56738,
                "latitude": 41.87194
              }
```
Mentre tutti i restanti hanno le proprie coordinate:

[locations.json](https://github.com/ondata/guida-api-istat/files/13840994/locations.json)

Altra cosa, qui ci sono tutti i dataflow: [https://ondata.github.io/guida-api-istat/rawdata/dataflow.xml](url) però non sono divisi per argomenti, quindi ho prima creato un json con tutti i dataflow, poi ho buttato il json con l'AI e gli ho chiesto di suddividerli per gruppi con titoli per le diverse categorie:

[categories.json](https://github.com/ondata/guida-api-istat/files/13841001/categories.json)

Le lascio qui per la community, se c'è qualcosa da migliorare anzi, ben venga, spero comunque aiuti :)

Grazie ancora @aborruso
