### ISSUE TITLE
Come si ottengono i valori di unità di misura?

### ISSUE THREAD

**Issue by JikuRoby** [ondata/guida-api-istat#22]
@aborruso 

Prendiamo questo esempio:

https://esploradati.istat.it/databrowser/#/it/dw/categories/IT1,Z0920ENV,1.0/UP2_ACC_AMBIEN/UP2_DCCN_SPESAPROTAMB/IT1,97_953_DF_DCCN_SPESAPROTAMB_1,1.0

In che unità di misura sono quei numeri? Lo scopriamo con un mouse hover sopra l'asterisco:

![Screenshot 2024-01-07 at 12 52 26](https://github.com/ondata/guida-api-istat/assets/66823132/19884a9a-092b-418f-bbfb-f512449e630b)

Cambiamo esempio:

https://esploradati.istat.it/databrowser/#/it/dw/categories/IT1,Z0920ENV,1.0/UP2_ACC_AMBIEN/UP2_DCCN_SPESAPROTAMB/IT1,97_953_DF_DCCN_SPESAPROTAMB_3,1.0

Stessa domanda, lo scopriamo facendo mouse hover sull'asterisco ma non nella stessa riga:

![Screenshot 2024-01-07 at 12 53 56](https://github.com/ondata/guida-api-istat/assets/66823132/44649be6-c2da-48d9-8da6-b0a64cd57d63)

Conseguentemente la domanda: dove troviamo il dato dell'unità di misura ed il suo valore quando usiamo le API?

Prendiamo il dato `97_953`: https://sdmx.istat.it/SDMXWS/rest/data/97_953

Non trovo l'unità di misura.

**Comment by JikuRoby** [comment]
@aborruso ok chiudo la issue perchè ho risolto. Però c'è un problema non indifferente e conviene aggiustare la guida.

La guida difatti dice di interrogare: `ITTER107` ma nel nuovo endpoint non è più quello ma `REF_AREA` per non sbagliare più che cambiare io ho messo:

`if (id === 'ITTER107' || id === 'TERRITORIO' || id === 'TERR_EVENTO' || id === 'TERR_RES' || id === 'RESIDENCE_TERR' || id === 'PLACE_REGISTR_EVENT' || id === 'REF_AREA') {`

Ma è un problema non da poco, perchè appena ISTAT dismetterà `https://sdmx.istat.it/` qualsiasi mappa in Italia che abbia seguito la guida non funzionerà più, poichè `ITTER107` non è più corretto.

Guarda qui:

https://esploradati.istat.it/SDMXWS/rest/availableconstraint/41_983

E guarda qui:

https://sdmx.istat.it/SDMXWS/rest/availableconstraint/41_983

`ITTER107` è diventato `REF_AREA`

**Comment by aborruso** [comment]
Ciao @JikuRoby purtroppo la guida è stata scritta diversa tempo fa, quando c'era un vuoto informativo importante.

È stata scritta in prima battuta a nostro uso, per avere un punto di partenza da cui iniziare a esplorare.

Quella di scriverne una nuova, è sicuramente una buona idea.

Grazie
