### ISSUE TITLE
Serve non raggiungibile?

### ISSUE THREAD

**Issue by JikuRoby** [ondata/guida-api-istat#24]
Sto provando da un paio d'ore ad accedere a:

[https://esploradati.istat.it/SDMXWS/rest/data/97_953](url)

Ma il server risponde con:

`Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.`

Oppure con:

`A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)`

Se uso questo endPoint funziona:

[https://sdmx.istat.it/SDMXWS/rest/data/97_953](url)

Ma tutta la nostra piattaforma usa l'endPoint: [esploradati.istat.it](url)

Sapete se ci stiano lavorando o se sia cambiato qualcosa? 

Grazie

**Comment by aborruso** [comment]
È tornata su?
