### ISSUE TITLE
http://sdmx.istat.it/SDMXWS/rest/ non funziona

### ISSUE THREAD

**Issue by Trinitro77** [ondata/guida-api-istat#25]
buongiorno,
il link http://sdmx.istat.it/SDMXWS/rest/  non funziona. Errore 404
sapete indicaremi il link nuovo ?
grazie

**Comment by aborruso** [comment]
Buongiorno @Trinitro77 qui i nuovi endpoint https://esploradati.istat.it/SDMXWS

**Comment by Trinitro77** [comment]
ok trovato, grazie mille !!!

**Comment by aborruso** [comment]
> ok trovato, grazie mille !!!

Grazie a te. Abbiamo messo una doverosa nota sulla guida

**Comment by Trinitro77** [comment]
Sto scoprendo questa nuova via ( per me) per accedere ai dati statistici in primis di Istat e poi delle altre istituzioni..
Senza la vostra preziosa guida non ci sarei riuscito..
grazie !!!
