### ISSUE TITLE
Postman collection API ISTAT

### ISSUE THREAD

**Issue by vincenzo-scia** [ondata/guida-api-istat#5]
Ciao @aborruso,
dopo aver letto la guida (davvero ben fatta, complimenti!) e visto il vostro webinar, ho pensato di creare una collection Postman delle API SDMX di ISTAT.

Perché proprio Postman?
1.  è free e multipiattaforma, il formato Postman Collection è open source
2. comodo e semplice, permette di salvare le chiamate in collection ordinate
3. permette di salvare dei "test" pre-request e post-request scritti in javascript
4. gestisce variabili d'ambiente e può essere usato per test-automation
5. può essere affiancato con Newman (open) che è il suo alter-ego in ambiente CLI

Ecco quindi cosa ho fatto:
1. seguendo la guida ed il cheatsheet ho settato tutti i parametri disponibili come variabili d'ambiente (es. {{agencyID}} = IT01) o come parametri delle chiamate
2. usando il tuo csv ho creato una collection di chiamate per tutti i dataflow disponibili, ordinate in cartelle
3. all'interno di ciascuna chiamata ai dataflow ho scritto un test con qualche riga di javascript (molto rudimentale, non sono un developer 😆) per salvare in automatico il resourceID e settarlo come variabile d'ambiente, in modo tale che si possano poi richiamare comodamente la dataStructure e la availableConstraint senza dover ricopiare il resourceID a mano
4. nella chiamata alla dataStructure, un test conta le dimensions in automatico e genera una stringa con n-1 punti (es. 4 dimensioni --> stringa "...") che viene salvata come variabile d'ambiente e inserita nella chiamata per ottenere i dati e facilitare così l'inserimento dei filtri

Non riesco a fare pull request sul repo, quindi lascio qui in allegato la collection e l'environment che contiene le variabili d'ambiente (basta togliere l'estensione .txt e importare i json dentro Postman).

Se pensi possa essere utile potremmo estendere la tua guida ed integrare un tutorial per testare queste API con Postman.

[ISTAT_SDMX_API.postman_collection.json.txt](https://github.com/ondata/guida-api-istat/files/4721206/ISTAT_SDMX_API.postman_collection.json.txt)
[ISTAT_SDMX_API.postman_environment.json.txt](https://github.com/ondata/guida-api-istat/files/4721209/ISTAT_SDMX_API.postman_environment.json.txt)

Vincenzo

**Comment by aborruso** [comment]
Ciao @vincenzo-scia ,
che piacere leggerti, grazie.

Penso che possa essere utile e gli farei proprio un paragrafo o un capitolo dedicato.
Il primo a imparare sarei io :)
Quindi proposta accettata.

Quindi scriverei il tutorial sul tuo lavoro e come usarlo in postman. Lo preparerei come una sezione distinta, che poi sicuramente integriamo nella principale (o come rimando o in blocco, da scegliere in seguito) e con tutti i credits del caso.

Chiunque dovrebbe poter fare una PR :(

Alla peggio fai un tuo minirepo con testo, eventuali immagini e file, e non appena pronto, lo integro io.

Grazie

**Comment by vincenzo-scia** [comment]
Ciao Andrea,
grazie a te :) perfetto allora questo weekend preparo il tutorial su postman. Al momento non sono riuscito a creare un branch sul tuo repo per poter fa, quindi l'ho forkato e ho iniziato a fare le modifiche sul mio fork che poi possiamo mergiare.

Intanto ho caricato sul fork la collection e l'environment postman + un diagramma che sintetizza i passi da fare per usare la collection, che poi descriverò per esteso nel tutorial:
https://github.com/vincenzo-scia/guida-api-istat/blob/postman/postman/istat_sdms_api_postman_workflow.png

**Comment by vincenzo-scia** [comment]
Ciao @aborruso,
ho completato il tutorial su postman sul fork: 
https://github.com/vincenzo-scia/guida-api-istat/tree/postman#come-interrogare-le-api-con-postman

Che ne pensi? Forse troppe immagini appesantiscono un po' troppo la guida?

**Comment by aborruso** [comment]
Ciao @vincenzo-scia ,
grazie mille!!

Ho Creato una sezione separata e ho palesato (come era doveroso) il tuo nome e cognome.

[![image](https://user-images.githubusercontent.com/30607/83790574-b3ccba80-a698-11ea-9a46-043aee5ca6ed.png)](https://ondata.github.io/guida-api-istat/index#come-interrogare-le-api-con-postman)

Ho inserito per tutte le immagini il path relativo.

Mi sembra un ottimo lavoro e ne daremo notizia la settimana prossima.

Grazie e buon fine settimana

**Comment by vincenzo-scia** [comment]
Grazie mille a te @aborruso! felice di aver dato un contributo a questa bella iniziativa
Ciao e buon weekend

A presto
