### ISSUE TITLE
API ISTAT e compatibilità con dati.istat.it e con il formato JSON

### ISSUE THREAD

**Issue by aromanino** [ondata/guida-api-istat#7]
Salve, 
come prima cosa voglio farvi i complimenti per il lavoro da voi svolto ed in particolar modo per il lavoro svolto da Andrea Borruso sulla guida delle API ISTAT e per il bellissimo webinar su sdmx  & API istat con Fabio Spagnuolo. Ho seguito la vostra guida ma ho dei dubbi su alcune cose e vorrei condividerle con voi. 
  

1.  Se da API chiedo la lista dei dataflow con la chiamata "**http://sdmx.istat.it/SDMXWS/rest/dataflow/IT1**" ottengo come risposta un sottoinsieme dei temi che sono consultabili su "dati.istat.it" nel menu di sinistra, un esempio "Spostamenti abituali per andare a scuola e a lavoro" che si trovano sotto il tema "servizi".  Questi tema mancanti infatti, non sono presenti nemmeno nel CSV di andrea al seguente link "**https://github.com/ondata/guida-api-istat/blob/master/processing/dataflow.csv**". Sto sbagliando qualcosa Io?

2. Per quanto riguarda il formato di risposta, impostando come header "Accept: application/json" sembrerebbe che non tutte le API  siano compliant con questo formatto, per esempio su questa risorsa "**http://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_ITTER107**" non ottengo una risposta congrua mentre in xml il tutto funziona magicamente. Sbaglio qualcosa?

Grazie A.

**Comment by aborruso** [comment]
Ciao @aromanino e grazie.



> * Se da API chiedo la lista dei dataflow con la chiamata "**http://sdmx.istat.it/SDMXWS/rest/dataflow/IT1**" ottengo come risposta un sottoinsieme dei temi che sono consultabili su "dati.istat.it" nel menu di sinistra, un esempio "Spostamenti abituali per andare a scuola e a lavoro" che si trovano sotto il tema "servizi".  Questi tema mancanti infatti, non sono presenti nemmeno nel CSV di andrea al seguente link "**https://github.com/ondata/guida-api-istat/blob/master/processing/dataflow.csv**". Sto sbagliando qualcosa Io?

Mi informo, ma credo che l'elenco che vedi sul sito ISTAT sia un elenco di query precotte, sulle API SDMX. Allo stesso risultato di queste puoi arrivare costruendo query personalizzate sulle API, sui dataflow.

> * Per quanto riguarda il formato di risposta, impostando come header "Accept: application/json" sembrerebbe che non tutte le API  siano compliant con questo formatto, per esempio su questa risorsa "**http://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_ITTER107**" non ottengo una risposta congrua mentre in xml il tutto funziona magicamente. Sbaglio qualcosa?

Non sbagli nulla, è come dici: credo che soltanto le query sui dati consentano formati di output diversi dall'XML.

Su entrambe le cose, appena posso verifico e torno qui.

Che stai facendo di bello con queste API?

**Comment by aromanino** [comment]
Ciao Andrea Grazie per la risposta, 
ti rispondo sotto, 
> Ciao @aromanino e grazie.
> 
> > * Se da API chiedo la lista dei dataflow con la chiamata "**http://sdmx.istat.it/SDMXWS/rest/dataflow/IT1**" ottengo come risposta un sottoinsieme dei temi che sono consultabili su "dati.istat.it" nel menu di sinistra, un esempio "Spostamenti abituali per andare a scuola e a lavoro" che si trovano sotto il tema "servizi".  Questi tema mancanti infatti, non sono presenti nemmeno nel CSV di andrea al seguente link "**https://github.com/ondata/guida-api-istat/blob/master/processing/dataflow.csv**". Sto sbagliando qualcosa Io?
> 
> Mi informo, ma credo che l'elenco che vedi sul sito ISTAT sia un elenco di query precotte, sulle API SDMX. Allo stesso risultato di queste puoi arrivare costruendo query personalizzate sulle API, sui dataflow.

Sul video del webinar al minuto 14:20 Fabio Spagnuolo se non erro dice che quando si clicca su una voce dei temi (tabella) essa punta al workflow. In ogni caso se cosi non fosse ritornando all'esempio su "spostamenti abituali per andare a scuola e a lavoro", non riesco ad individuare un dataflow dove poter fare delle query per ottenere i dati esposti da dati.istat.it.
Ti ringrazio.


> 
> > * Per quanto riguarda il formato di risposta, impostando come header "Accept: application/json" sembrerebbe che non tutte le API  siano compliant con questo formatto, per esempio su questa risorsa "**http://sdmx.istat.it/SDMXWS/rest/codelist/IT1/CL_ITTER107**" non ottengo una risposta congrua mentre in xml il tutto funziona magicamente. Sbaglio qualcosa?
> 
> Non sbagli nulla, è come dici: credo che soltanto le query sui dati consentano formati di output diversi dall'XML.
> 
> Su entrambe le cose, appena posso verifico e torno qui.
> 
> Che stai facendo di bello con queste API?

Faccio una breve introduzione per farti capire il motivo per cui vogliamo usare le API.  Lavoro per il CRS4(www.crs4.it), un centro di ricerca ed attualmente stiamo lavorando ad un progetto in ambito “Smart Cities” denominato Cagliari2020 (http://www.crs4.it/it/projectdetails/61981d62-b567-1032-95fe-0030485a3848/). All’ interno del nostro Team di lavoro abbiamo sviluppato un framework basato su un architettura a microservizi chiamato CMC(CRS4 Microservice Core) rilasciato in Open source su github (https://github.com/smartenv-crs4). Per esigenze di progetto(Cagliari2020), sulla base di CMC abbiamo poi sviluppato  una piattaforma IoT general purpose a microservizi per la gestione dei dati provenienti dai diversi devices. Oltre ai dati provenienti dai sensori abbiamo individuato interessanti i dati esposti da ISTAT(grazie anche alla vostra attività). Stavamo quindi pensando di integrarli nella nostra piattaforma IOT tramite lo sviluppo di in connettore(Middleware).
 In attesa di una tua risposta saluti A.

**Comment by aborruso** [comment]
Ciao @aromanino 

> In ogni caso se cosi non fosse ritornando all'esempio su "spostamenti abituali per andare a scuola e a lavoro", non riesco ad individuare un dataflow dove poter fare delle query per ottenere i dati esposti da dati.istat.it.
> Ti ringrazio.

se dal sito fai click qui, ricavi l'ID del dataset, che è `DCCV_AVQ_PERSONE`

![image](https://user-images.githubusercontent.com/30607/86288816-dd6ef800-bbea-11ea-81e9-c8f93c62145e.png)

Da questo ricavi che il dataflow è `83_63`.

Se ti scarichi i _costraint_ del dataflow, mi sembra (a caldo e rapidamente) che ci siano disponibili i parametri per costruire la query che cerchi.

```
curl "http://sdmx.istat.it/SDMXWS/rest/availableconstraint/83_63" >83_63_availableconstraint.xml
```

**Comment by aromanino** [comment]
> Ciao @aromanino
> 
> > In ogni caso se cosi non fosse ritornando all'esempio su "spostamenti abituali per andare a scuola e a lavoro", non riesco ad individuare un dataflow dove poter fare delle query per ottenere i dati esposti da dati.istat.it.
> > Ti ringrazio.
> 
> se dal sito fai click qui, ricavi l'ID del dataset, che è `DCCV_AVQ_PERSONE`
> 
> ![image](https://user-images.githubusercontent.com/30607/86288816-dd6ef800-bbea-11ea-81e9-c8f93c62145e.png)
> 
> Da questo ricavi che il dataflow è `83_63`.
> 
> Se ti scarichi i _costraint_ del dataflow, mi sembra (a caldo e rapidamente) che ci siano disponibili i parametri per costruire la query che cerchi.
> 
> ```
> curl "http://sdmx.istat.it/SDMXWS/rest/availableconstraint/83_63" >83_63_availableconstraint.xml
> ```

Benissimo Grazie ;)

**Comment by aborruso** [comment]
@aromanino se per te è ok, per favore chiudi issue.

Grazie
